<a href="https://colab.research.google.com/github/samp3209/personalprojects/blob/main/MarkovChainProbability_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
t = 0
current_answer = np.matrix([0.7, 0.2, 0.1])
transition = np.matrix([[0.0, 0.6, 0.4],
                        [0.7, 0.3, 0.0],
                        [0.2, 0.8, 0.0]])
tolerance = 1e-10

In [52]:
t1 = current_answer.dot(transition)
t1 /= np.sum(t1)
print(t1)

[[0.16 0.56 0.28]]


In [53]:
t2 = t1.dot(transition)
print(t2)

[[0.448 0.488 0.064]]


In [65]:
def recursion_mark(current_answer, transition, tolerance, i):
  next = current_answer.dot(transition)
  next /= np.sum(next)
  if np.allclose(current_answer, next, atol=tolerance):
    return next, i
  else:
    return recursion_mark(next, transition, tolerance, i+1)

recursion_mark(current_answer, transition, tolerance, t)


(matrix([[0.36842113, 0.48421038, 0.1473685 ]]), 17)