<a href="https://colab.research.google.com/github/samp3209/personalprojects/blob/main/NeuralNetworkSandbox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.random.seed(0)

def sigmoid(x):
	return 1 / (1 + np.exp(-x))

def neural_net(W, V, b, c, x):
	z = sigmoid(np.dot(W.T, x.reshape((2,1))) + b.reshape((4, 1)))
	y = sigmoid(np.dot(V.T, z) + c)
	return y, z


In [3]:

W = np.random.uniform(-10, 10, (2,4))
V = np.random.uniform(-10, 10, (4, 1))

b = np.random.uniform(-10, 10, 4)
c = np.random.uniform(-10, 10, 1)

x = np.array([1., 2.])
y = np.array([1.])

print(W)
print(V)
print(b)
print(c)

[[ 6.65239691  5.56313502  7.40024296  9.57236684]
 [ 5.98317128 -0.77041275  5.61058353 -7.63451148]]
[[ 2.79842043]
 [-7.13293425]
 [ 8.89337834]
 [ 0.43696644]]
[-1.7067612  -4.70888776  5.48467379 -0.87699336]
[1.36867898]


In [4]:
print(neural_net(W, V, b, c, x)[0])

def BCE_loss(W, V, b, c, x, y):
	y_hat, z = neural_net(W, V, b, c, x)
	return -y * np.log(y_hat) - (1 - y) * np.log(1 - y_hat)

y_pred, z =neural_net(W, V, b, c, x)

def grad_w():
	g1 = (y-2*y*y_pred+y_pred)*V   # 4x1
	print(g1.shape)
	g2 = z*(1-z)					# 4x1
	print(g2.shape)
	g3 = x.reshape((2,1))							# 2x1
	return (g1*g2).dot(g3.T)

print(-grad_w())

[[0.99997684]]
(4, 1)
(4, 1)
[[-2.93015744e-12 -5.86031488e-12]
 [ 3.67925057e-05  7.35850115e-05]
 [-6.99335472e-15 -1.39867094e-14]
 [-1.40959048e-08 -2.81918096e-08]]


Second set of code

In [5]:
import numpy as np
np.random.seed(0)
import torch
import torch.nn as nn

W = np.random.uniform(-10, 10, (2, 4))
V = np.random.uniform(-10, 10, (4, 1))

b = np.random.uniform(-10, 10, 4)
c = np.random.uniform(-10, 10, 1)

class neural_net(nn.Module):
	def __init__(self):
		super(neural_net, self).__init__()
		self.fc1 = nn.Linear(2, 4)
		self.fc1.weight.data = torch.tensor(W.T, dtype=torch.float)
		self.fc1.bias.data = torch.tensor(b, dtype=torch.float)
		self.fc2 = nn.Linear(4, 1)
		self.fc2.weight.data = torch.tensor(V.T, dtype=torch.float)
		self.fc2.bias.data = torch.tensor(c, dtype=torch.float)


	def forward(self, x):
		x = torch.sigmoid(self.fc1(x))
		x = torch.sigmoid(self.fc2(x))
		return x


x = torch.tensor([1., 2.])
y = torch.tensor([1.])

net = neural_net()
criterion = nn.BCELoss()

y_pred = net(x)
loss = criterion(y_pred, y)

loss.backward()

print(net.fc1.weight.grad)


tensor([[-2.0439e+00, -4.0878e+00],
        [ 0.0000e+00,  0.0000e+00],
        [-7.0506e-04, -1.4101e-03],
        [-1.4195e-04, -2.8390e-04]])
